version: "3.8"

services: 

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    entrypoint: "/app/entrypoint.sh"
    depends_on: 
      - mysql_server
      - rabbitmq

  worker:
    build: 
      context: .
      dockerfile: Dockerfile_worker
    volumes: 
      - .:/app
      - '/app/node_modules'
    entrypoint: "/app/entrypoint2.sh"
    depends_on: 
      - mysql_server
      - rabbitmq
      
  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=killian
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306 
  
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672